name: Publish Release

on:
  release:
    types: published

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  package:
    name: Package crate
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: cargo login ${{ secrets.CARGO_TOKEN }}
      - name: Package
        run: cargo package

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: cargo login ${{ secrets.CARGO_TOKEN }}
      - name: Publish
        run: cargo publish
